mod_def = {}

mod_def["NODES"] = {
    "NAME": "NODES",
    "TABLE": "NODES",
    "ROWID": "NODES_ID",
    "CONTEXT_ROW": None,
    "COLS": [
        {
         "CATEGORY": "ROW",
         "NAME": "NODES_ID",
         "HEADER": "ID",
         "TYPE": "INT",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 0,
        },
        {
         "CATEGORY": "ROW",
         "NAME": "NODES_INSERTED",
         "HEADER": "CREATED",
         "TYPE": "STR",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 0,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_API_KEY",
         "HEADER": "API_KEY",
         "TYPE": "ASCII",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_NAME",
         "HEADER": "NAME",
         "TYPE": "STR",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 0,
         "DEFAULT": 1,
         "NEW": 1,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_DESCRIPTION",
         "HEADER": "DESCRIPTION",
         "TYPE": "STR",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 0,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_READONLY",
         "HEADER": "READONLY",
         "TYPE": "BOOL",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "DEFAULT": 1,
         "NEW": 1,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_DBA",
         "HEADER": "DBA",
         "TYPE": "BOOL",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "DEFAULT": 1,
         "NEW": 1,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_IP",
         "HEADER": "IP",
         "TYPE": "STR",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 0,
         "DEFAULT": 1,
         "NEW": 1,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_EXPIRE",
         "HEADER": "EXPIRE",
         "TYPE": "TIMESTAMP",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "DEFAULT": 1,
        },
        {
         "CATEGORY": "NODE",
         "NAME": "NODES_ENABLED",
         "HEADER": "ENABLED",
         "TYPE": "BOOL",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "DEFAULT": 1,
         "NEW": 1,
         "DEFAULT_VALUE": 1,
        },
        {
         "CATEGORY": "RELATIONSHIP",
         "NAME": "NODES_PEOPLE_ID",
         "HEADER": "PERSON",
         "TYPE": "ID",
         "ID_API": "PEOPLE",
         "SIZE": 50,
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "INTERNAL": 0,
         "DEFAULT": 0,
        },
        {
         "CATEGORY": "RELATIONSHIP",
         "NAME": "NODES_ASSETS_ID",
         "HEADER": "ASSET",
         "TYPE": "ID",
         "ID_API": "ASSETS",
         "SIZE": 50,
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "INTERNAL": 0,
         "DEFAULT": 0,
        },
    ],
    "ORDER": ["NODES_NAME"]
}
