mod_def = {}

mod_def["LISTS"] = {
    "NAME": "LISTS",
    "TABLE": "LISTS",
    "ROWID": "LISTS_ID",
    "CONTEXT_ROW": None,
    "COLS": [
        {
         "NAME": "LISTS_ID",
         "HEADER": "ID",
         "TYPE": "INT",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 0,
        },
        {
         "NAME": "LISTS_NAME",
         "HEADER": "NAME",
         "TYPE": "STR",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 1,
         "NEW": 1,
         "DEFAULT": 1,
        },
        {
         "NAME": "LISTS_INTERNAL",
         "HEADER": "INTERNAL",
         "TYPE": "BOOL",
         "EDIT": 0,
         "QUERY": 0,
         "SEARCH": 0,
         "REQUIRED": 0,
        },
    ],
    "ORDER": ["LISTS_NAME"]
}

mod_def["LIST_ITEMS"] = {
    "NAME": "LIST_ITEMS",
    "TABLE": "LIST_ITEMS",
    "ROWID": "LIST_ITEMS_ID",
    "CONTEXT_ROW": "LIST_ITEMS_LISTS_ID",
    "COLS": [
        {
         "NAME": "LIST_ITEMS_ID",
         "HEADER": "ID",
         "TYPE": "INT",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 0,
        },
        {
         "NAME": "LIST_ITEMS_LISTS_ID",
         "HEADER": "LIST",
         "TYPE": "ID",
         "ID_API": "LISTS",
         "EDIT": 0,
         "QUERY": 1,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 0,
        },
        {
         "NAME": "LIST_ITEMS_VALUE",
         "HEADER": "VALUE",
         "TYPE": "STR",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 1,
         "NEW": 1,
         "DEFAULT": 1,
        },
        {
         "NAME": "LIST_ITEMS_DESCRIPTION",
         "HEADER": "DESCRIPTION",
         "TYPE": "STR",
         "EDIT": 1,
         "QUERY": 1,
         "SEARCH": 1,
         "REQUIRED": 1,
         "NEW": 1,
         "DEFAULT": 1,
        },
        {
         "NAME": "LIST_ITEMS_ENABLED",
         "HEADER": "ENABLED",
         "TYPE": "BOOL",
         "EDIT": 1,
         "QUERY": 0,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 1,
         "DEFAULT": 1,
         "DEFAULT_VALUE": 1,
        },
        {
         "NAME": "LIST_ITEMS_ORDER",
         "HEADER": "ORDER",
         "TYPE": "FLOAT",
         "EDIT": 1,
         "QUERY": 0,
         "SEARCH": 0,
         "REQUIRED": 0,
         "NEW": 1,
         "DEFAULT": 1,
         "DEFAULT_VALUE": 999,
        },
        {
         "NAME": "LIST_ITEMS_INTERNAL",
         "HEADER": "INTERNAL",
         "TYPE": "BOOL",
         "EDIT": 0,
         "QUERY": 0,
         "SEARCH": 0,
         "REQUIRED": 0,
        },
    ],
    "ORDER": ["LIST_ITEMS_ORDER", "LIST_ITEMS_VALUE"]
}
